var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/join/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ldtv56._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_3kxm..js")
R.c("server/chunks/ssr/[root-of-the-server]__0gd~hd7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/node_modules_@swc_helpers_cjs_05_rdru._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jn2mgt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_join_[id]_page_actions_0o_jnbk.js")
R.m(96331)
module.exports=R.m(96331).exports
