var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/create/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yi8gc4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10r6rja.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gd~hd7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/node_modules_@swc_helpers_cjs_05_rdru._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jn2mgt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_create_page_actions_0yb7zz0.js")
R.m(11893)
module.exports=R.m(11893).exports
